title: Project
pages: 
  template: 
    - livrable
    - slideshow 
  hide: true
files: true
fields:
  title:
    label: Title
    type:  text
  description: 
    label: Description
    type: textarea
  mysubpagelist:
    label: Slideshows 
    type:  subpagelist